// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CreateProject: typeof import('./src/components/create-project/index.vue')['default']
    CreateProjectForm: typeof import('./src/components/CreateProjectForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('./src/components/create-project/Form.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}

export { }
